root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go build -o ./tmp/main ."
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "templ"]
exclude_dir = ["assets", "tmp", "vendor", ".git"]
include_dir = []
exclude_file = []
delay = 200
send_interrupt = true
kill_delay = 500
stop_on_error = true
rerun = true
rerun_delay = 500

[log]
time = true
level = "debug"

[screen]
clear_on_rebuild = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true 